# Generated by Django 5.0.3 on 2024-04-23 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='join_requests',
            field=models.ManyToManyField(related_name='join_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
