# Generated by Django 5.0.3 on 2024-03-17 12:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('num_people_required', models.IntegerField()),
                ('tags', models.CharField(max_length=100)),
                ('paperid', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(max_length=100)),
                ('project_desc', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('num_people_required', models.IntegerField()),
                ('tags', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=datetime.datetime(2024, 3, 17, 12, 29, 22, 389297, tzinfo=datetime.timezone.utc), max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='prn',
            field=models.CharField(default=datetime.datetime(2024, 3, 17, 12, 29, 40, 792162, tzinfo=datetime.timezone.utc), max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
