# Generated by Django 5.0.3 on 2024-04-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_paper_project_rename_username_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='project_thumbnail/'),
        ),
    ]
