# Generated by Django 5.0.3 on 2024-04-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_project_join_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='join_requests',
        ),
    ]
