# Generated by Django 5.0.3 on 2024-04-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='backend\\myproject\\media\\proj_thumbnails'),
        ),
    ]
