# Generated by Django 5.0.3 on 2024-04-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='backend\\myproject\\media\\project_thumbnail'),
        ),
    ]
