# Generated by Django 5.0.3 on 2024-04-22 21:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_projectuser_user_alter_userinterest_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='joinRequests',
        ),
        migrations.AddField(
            model_name='project',
            name='joinRequests',
            field=models.ForeignKey(blank=True, default=datetime.datetime(2024, 4, 22, 21, 27, 49, 299944, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
