# Generated by Django 5.0.3 on 2024-04-22 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_project_joinrequests_project_joinrequests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='joinRequests',
        ),
        migrations.AddField(
            model_name='project',
            name='joinRequests',
            field=models.ManyToManyField(blank=True, related_name='join_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
